{% set version = "1.26.0" %}

package:
  name: python-ecmwf_grib
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: 0ca45544c54a3a67de78a62663d4be6be8d9c95a63f1bd30fcb4c14588ac9501

build:
  number: 0
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python
    - numpy 1.8.*
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf 4.4.*
    - hdf5 1.10.1
    - ecmwf_grib {{ version }}
  run:
    - python
    - numpy >=1.8
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf 4.4.*
    - hdf5 1.10.1
    - ecmwf_grib {{ version }}

test:
  imports:
    - gribapi
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]


about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache-2.0
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - kmuehlbauer
    - kynan
