{% set version = "1.19.0" %}

package:
  name: python-ecmwf_grib
  version: {{ version }}

source:
  fn: grib_api-{{ version }}.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: caec66c2d54331de9830dde853195262a1859bab36d5d03b4d44ac55784d921d

build:
  number: 1
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python
    - numpy x.x
    - jasper
    - libpng >=1.6.23,<1.7
    - libnetcdf 4.4.*
    - ecmwf_grib {{ version }}
  run:
    - python
    - numpy x.x
    - jasper
    - libpng >=1.6.23,<1.7
    - libnetcdf 4.4.*
    - ecmwf_grib {{ version }}

test:
  imports:
    - gribapi
  commands:
    #- conda inspect linkages -p $PREFIX python-ecmwf_grib  # [not win]
    #- conda inspect objects -p $PREFIX python-ecmwf_grib  # [osx]


about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache-2.0
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - kmuehlbauer
    - kynan
