{% set version = "1.27.0" %}

package:
  name: python-ecmwf_grib
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
  sha256: adf54b649da4eb25aee8eb9a8f9fa2de3f0ea318c597be056cbb7c28535fa6ef

build:
  number: 1
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - ecmwf_grib {{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - ecmwf_grib {{ version }}

test:
  imports:
    - gribapi
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]


about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache-2.0
  summary: 'The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - kmuehlbauer
    - kynan
