# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ku5/bWIRXrqNfSzZYkJZIesuMTingbpGCB2bhl1pWVMsMmKmfBDUmqEcWtnjpGE3ICoxkf4Omg4mu6a5ROk5nSeO75VQEk399hhSyCoFxP3f0uO8l83FuxH1RFwJvwT0Gz+a1GfSJUyJJtGkU0p9MW5HWaA7MjT07uZ7450JaFvk+q7dBJepeXXQ89uZMzTGJaSl3htMLyQH5SZyKVGcHvBz9zQsPWC9C3QrGqZFLgtn3pErs2FS0B/VS+Rtk+MMsfwUWT4u9xJC1B8b+f4Nx+odDq4lw1UGFTsvKSxohqTJ97wrte2KGzVZW01EDUD9YcktfbyG1+yTqSlgGn9RUczUi+0OoDlrtZGAZ64ebNq+F2CJTav6BNfptHs8tcN+OUDOyV/Ypg03zvXhJh+wfQSvxGY+LdlvM5va9Js8+I1CIay0Xf6l1JO4YrQvkFUTJWRI1Wwdc9Ld5lsw4Ju1f2lqiPTjizb9LmCilo0TTv82s3PcYSIDzduq0nYJux5V+320nfI1/JveMyOjzrKx7AYq5HeK1vlyHLKpFuzatUahQwjMLMDCAHTZdlTfuO/YjGg+ImuJK4ftptW16hEE/adxbmZr7BbMz+oq6Rd7TqOpq8aYlCCzI/RvyOfer0U8qC9m887L8kExXA7Q20BDTv1IP0E4Tc+pUXdqPqo3dUs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
