travis:
  secure:
    BINSTAR_TOKEN: ku5/bWIRXrqNfSzZYkJZIesuMTingbpGCB2bhl1pWVMsMmKmfBDUmqEcWtnjpGE3ICoxkf4Omg4mu6a5ROk5nSeO75VQEk399hhSyCoFxP3f0uO8l83FuxH1RFwJvwT0Gz+a1GfSJUyJJtGkU0p9MW5HWaA7MjT07uZ7450JaFvk+q7dBJepeXXQ89uZMzTGJaSl3htMLyQH5SZyKVGcHvBz9zQsPWC9C3QrGqZFLgtn3pErs2FS0B/VS+Rtk+MMsfwUWT4u9xJC1B8b+f4Nx+odDq4lw1UGFTsvKSxohqTJ97wrte2KGzVZW01EDUD9YcktfbyG1+yTqSlgGn9RUczUi+0OoDlrtZGAZ64ebNq+F2CJTav6BNfptHs8tcN+OUDOyV/Ypg03zvXhJh+wfQSvxGY+LdlvM5va9Js8+I1CIay0Xf6l1JO4YrQvkFUTJWRI1Wwdc9Ld5lsw4Ju1f2lqiPTjizb9LmCilo0TTv82s3PcYSIDzduq0nYJux5V+320nfI1/JveMyOjzrKx7AYq5HeK1vlyHLKpFuzatUahQwjMLMDCAHTZdlTfuO/YjGg+ImuJK4ftptW16hEE/adxbmZr7BbMz+oq6Rd7TqOpq8aYlCCzI/RvyOfer0U8qC9m887L8kExXA7Q20BDTv1IP0E4Tc+pUXdqPqo3dUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
