travis:
  secure:
    BINSTAR_TOKEN: nouENRSTROtxm70qIzfr6EpyU17gqkj+NMAnG70HgdXdsLCWd0KLGRaNMaePbbCabXHe2wEI6fHPZD9588ilZGWOfzdMq9QgDGZkrsUn8PRZfg/KZI+2Vha8MdqTvSWsbh7l2lXF827fLQY8RIflLgPFfCUgCuBQOuVFVWmUoiVnzwJuWYzsly4Rhxp4jSPRCZuiPyan7g6zUzACj973Pzoouud3zh0+dQ5JPi22MzGPkTuNc6yBD7Ht+Ks54z0nLCHcZj2DmIky0mahozRJ/Ou26iadJcfg196Lc/0a1rWXNLyW+B6urx4Ee5Xk9IycSqTU7QS4zxps4DF2YdcwGzKpk6MwLVCwg88C/IXRqfyvkvgZFuRmQbSmJlN0lD6+ndkwHxtbHDDcxEJyHzd7QOQyIlQkHgUsx6P+xRoM2u8Bl/yw/r4TdkHsIEjRCarV1dy3wuddCz2OH/SgMXGo6N6/V5Ep9diez8PHxXoo5yef0Byq3gk37yoCcn+HBpj0URYJ62z/a585iXrEd5Gv8OdyBYFpiD6bFkPv00kxi0bv+olggMltFB7LCfim0c4z9Edb8b2bFTu0ZF4nokDRqS5A0WyhxknoBsABGVz9KaaW7z56xsNh4v5rgk8BUH1GYY5ZY9QuhAQse22fFHNxfdofLiyu3UqT7rGJg6bk+TQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
